# Лабораторная работа 2


## Встроенные типы объектов в Pyhon

*Ляпунова Арина 20.03* 

## Задание 1.

**Построение иерархии встроенных типов в Python**: myGraf.png

<img src='C:\Users\arish\OneDrive\Изображения\Снимки экрана\myGraf.png' width=1000, heigth=1000>

## Задание 2.

**2.1 Проработка примеров, представленных в лекционном файле**

## 2.2 Встроенные типы объектов, представляющих числа

In [10]:
import decimal as dec
print(0.5+0.15, dec.Decimal('0.5')+dec.Decimal('0.15'))
print(0.5+0.15, dec.Decimal('0.5')-dec.Decimal('0.15'))
print(0.5+0.15, dec.Decimal('0.5')//dec.Decimal('0.15'))
print(0.5+0.15, dec.Decimal('0.5')*dec.Decimal('0.15'))

0.65 0.65
0.65 0.35
0.65 3
0.65 0.075


In [11]:
import fractions as frac
print(0.5 + 0.15, frac.Fraction(1, 2) + frac.Fraction(3, 20)) 
print(0.5 + 0.15, frac.Fraction(1, 2) - frac.Fraction(3, 20))  
print(0.5 + 0.15, frac.Fraction(1, 2) // frac.Fraction(3, 20))  
print(0.5 + 0.15, frac.Fraction(1, 2) * frac.Fraction(3, 20)) 

0.65 13/20
0.65 7/20
0.65 3
0.65 3/40


## 2.3 Встроенные типы последовательностей: str, list, tuple

***1) Строка***

- нарезание и конкатенация:

In [15]:
S = 'spam'
S = S[:1] + 'l' + S[2:]
print(S)

slam


- индексация и конкатенация:

In [17]:
S = 'spam'
S = S[0] + 'l' + S[2:]
print(S)

slam


- присваивание по индексу(не сработает, строки в Python неизменяемы):

In [41]:
S = ' spam'
S[1]='l'
print(s)

TypeError: 'str' object does not support item assignment

***2)Список***

- нарезание и конкатенация:

In [45]:
L=list('spam')
L = L[:1] + ['l'] + L[2:]  
print(L) 

['s', 'l', 'a', 'm']


- индексация и конкатенация(не сработает, возвращаемый объект типа str, a мы не можем складывать строки и списки):

In [48]:
L=list('spam')
L = L[0] + ['l'] + L[2:]  
print(L)

TypeError: can only concatenate str (not "list") to str

- присваивание по индексу:

In [51]:
L = ['s', 'p', 'a', 'm']
L[1] = 'l'
print(L)

['s', 'l', 'a', 'm']


***3)Кортежи***

- нарезание и конкатенация:

In [55]:
T = ('s', 'p', 'a', 'm')
T= T[:1] + ('l',) + T[2:]
print(T)

('s', 'l', 'a', 'm')


- индексация и конкатенация

In [58]:
T = ('s', 'p', 'a', 'm')
T = (T[0],) + ('l',) + T[2:]
print(T)

('s', 'l', 'a', 'm')


- присваивание по индексу(не сработает, кортежи, как и строки, в Python неизменяемы)

In [61]:
T = ('s', 'p', 'a', 'm')
T[1] = 'l'
print(T)

TypeError: 'tuple' object does not support item assignment

## 2.4 Встроенный тип отображения: dict

In [64]:
personal_info = {
    "name": {"first_name": "Арина", "middle_name": "Дельман", "last_name": "Марьевна"},
    "age": 17,
    "workplace": "безработная",
    "address": "ул.Пушкина, д.1, кв.1",
    "email": "exexe@gmail.com",
    "phone_number": "+375 75 77 35 75"
}


print(personal_info["name"]["first_name"])     
print(personal_info["age"])                    
print(personal_info["workplace"])             
print(personal_info["address"])               
print(personal_info["email"])                  
print(personal_info["phone_number"])          

Арина
17
безработная
ул.Пушкина, д.1, кв.1
exexe@gmail.com
+375 75 77 35 75


Словари не поддерживают позиционное упорядочение слева направо, как последовательности. Обращение к значению словаря/индексация словаря
происходит по ключу.Внутренне словари реализованы как хеш-таблицы, обеспечивая очень быстрое извлечение элементов. Поэтому словарь является более осмысленной структурой для данной задачи.

## 2.5 Встроенный тип множества: set

Пример удаления повторяющихся символов строки с использованием множества:

In [69]:
list1 = list(range(0,10,3))*2
print(list1)
list1 = list(set(list1))
print(list1)

[0, 3, 6, 9, 0, 3, 6, 9]
[0, 9, 3, 6]


## 2.8. Интерфейс объекта: операции и методы

*Примеры вызова методов count и index:*

***1) Списки***(поддерживают `count` и `index`)

In [74]:
list = [1,2,3,4,6,2,3,5,7,1,8,2]

print(list.count(2)) 
print(list.index(1))  

3
0


***2) Строки***(поддерживают `count` и `index`)

In [77]:
string = "helo everynyan"

print(string.count('l')) 
print(string.index('e')) 

1
1


***3) Кортежи***(поддерживают `count` и `index`)

In [80]:
tuple = (1, 2, 3, 4, 5, 2, 4, 1)

print(tuple.count(2))  
print(tuple.index(2)) 

2
1


***4) Множества***(не поддерживают `count` и `index`)

In [83]:
set = {1, 2, 3, 2, 4, 2}

print(set.count(2)) 
print(set.index(2)) 

AttributeError: 'set' object has no attribute 'count'

***5) Словари***(не поддерживают `count` и `index`)

In [86]:
dict = {'a': 1, 'b': 2, 'c': 3, 'd': 2}

print(dict.count('d')) 
print(dict.index('b'))  

AttributeError: 'dict' object has no attribute 'count'

*Пример выражения, в котором для заданной строки последовательно применены три различных строковых метода:*

In [89]:
text = "Neskvik and milk "
result = text.strip().lower().replace("milk","beer")
print(result) 

neskvik and beer


`strip():`
Удаляет пробельные символыс начала и конца строки. Если строка начинается или заканчивается одним или несколькими пробельными символами, метод strip() удаляет их, оставляя только основную часть строки.
`lower():`
Переводит все заглавные буквы в строчные, оставляя все остальные символы без изменений.
`replace(old, new):`
Ищет все вхождения указанной подстроки old и заменяет их на указанную подстроку new. Если искомая подстрока отсутствует, возвращается оригинальная строка.

*Примеры добавления элемента в список:*

`1) append`

In [94]:
list= ['a', 'b', 'c']   
list.append('d')
print(list)

['a', 'b', 'c', 'd']


`2) insert`

In [97]:
list = ['a', 'b', 'c']     
list.insert(0, 'z') 
print(list)

['z', 'a', 'b', 'c']


`3)extend`

In [100]:
list = ['a', 'b', 'c']  
list.extend(['d','z'])
print(list)

['a', 'b', 'c', 'd', 'z']


*Пример сортировки списка с использованием метода `sort` и
заданного аргумента `key`*

In [103]:
words = ["apple", "banana", "milk"]
words.sort(key=len)
print(words) 

['milk', 'apple', 'banana']


Исходный список oтсортируем по возрастанию длины. Функция len() применяется к каждому слову в списке, чтобы определить его длину.В результате слова сортируются по возрастанию длины.

In [106]:
numbers = [8, 3, 9, 1, 5, 2]
numbers.sort()
print(numbers)

[1, 2, 3, 5, 8, 9]



 По умолчанию метод sort() сортирует числа в порядке возрастания, так как числа уже имеют естественный порядок.

*Словарь из 100 элементов с одинаковыми значениями:*

In [110]:
dictionary = dict.fromkeys(range(1, 101), "i love cats")
print(dictionary)

{1: 'i love cats', 2: 'i love cats', 3: 'i love cats', 4: 'i love cats', 5: 'i love cats', 6: 'i love cats', 7: 'i love cats', 8: 'i love cats', 9: 'i love cats', 10: 'i love cats', 11: 'i love cats', 12: 'i love cats', 13: 'i love cats', 14: 'i love cats', 15: 'i love cats', 16: 'i love cats', 17: 'i love cats', 18: 'i love cats', 19: 'i love cats', 20: 'i love cats', 21: 'i love cats', 22: 'i love cats', 23: 'i love cats', 24: 'i love cats', 25: 'i love cats', 26: 'i love cats', 27: 'i love cats', 28: 'i love cats', 29: 'i love cats', 30: 'i love cats', 31: 'i love cats', 32: 'i love cats', 33: 'i love cats', 34: 'i love cats', 35: 'i love cats', 36: 'i love cats', 37: 'i love cats', 38: 'i love cats', 39: 'i love cats', 40: 'i love cats', 41: 'i love cats', 42: 'i love cats', 43: 'i love cats', 44: 'i love cats', 45: 'i love cats', 46: 'i love cats', 47: 'i love cats', 48: 'i love cats', 49: 'i love cats', 50: 'i love cats', 51: 'i love cats', 52: 'i love cats', 53: 'i love cats', 5

## 2.9 Переменная

*Примеры циклического объекта для различных встроенных типов:*

***1) Списки***

In [115]:
list = []
list.append(list) 
print(list)       

[[...]]


***2) Кортежи***(т.к они неизменяемы, то могут содержать ссылки на сами себя напрямую. Но можно создать вложенный кортеж, который будет ссылаться на внешний кортеж:)

In [118]:
tuple = ()
nested_tuple = (tuple,)
tuple += nested_tuple 
print(tuple)         

((),)


***3) Словари***

In [121]:
dict = {}
dict['this'] = dict 
print(dict)        

{'this': {...}}


***4) Строки***

Строки не могут содержать ссылки на сами себя, так как они неизменяемы и не поддерживают механизм ссылок

***5) Множества***

Множества также не могут содержать ссылки на сами себя, так как они основаны на хэш-таблицах и требуют уникальности элементов


***6) Числа***

In [128]:
a = [1,2]; a.append(a)
a

[1, 2, [...]]

*Cоздание объекта, на который ссылаются четыре переменные:*

In [131]:
import sys
a = b = c = d = [15]
sys.getrefcount(a)

5

sys.getrefcount() возвращает количество ссылок на объект, включая дополнительную временную ссылку, созданную самой функцией getrefcount()

*Три различных способа копирования списка:*

***1) Copy***

In [136]:
 a = [1,2,3]                    
 c = a.copy() 
print(c)

[1, 2, 3]


***2)Срез всей последовательности***

In [139]:
a = [1,2,3]
c = a[:]
print(c)

[1, 2, 3]


***3)C помощью вызова соответствующих функций-конструкторов***

In [142]:
a = [1, 2, 3]
c = a.__class__(a) 
print(c)

[1, 2, 3]


## 2.10 Выражение спискового включения

*Примеры создания множества с использованием синтаксиса
включения с условием:*

In [146]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
new_list = {x for x in list if x % 3 == 0}
print(new_list)

{9, 3, 6}


In [148]:
string = ["apple", "banana", "milk", "beer", "meat"]
mew_string = {s for s in string if len(s) > 4}
print(mew_string)

{'banana', 'apple'}


*Пример создания числовой матрицы размера 7 × 8 с использованием включений и с помощью `numpy`:*

In [151]:
matrix = [[j for j in range(8)] for i in range(7)]
print(matrix)

[[0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7]]


In [153]:
import numpy as np
matrix = np.arange(1, 57).reshape(7, 8)
print(matrix)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]]


*Пример создания словаря с использованием синтаксиса включения с двумя уровнями вложенности:*

In [156]:
squares_and_cubes = {num: {'square': num**2, 'cube': num**3} for num in range(1, 3)}
print(squares_and_cubes)

{1: {'square': 1, 'cube': 1}, 2: {'square': 4, 'cube': 8}}


## 2.11 Форматированный вывод строк

***1)Форматированный вывод***

In [160]:
m = 5.0  
a = 9.8  
print(f'Умножив {m=:.1f} кг на ускорение свободного падения {a=:.1f} м/с², получим силу F = {m*a:=.2f} Н.')

Умножив m=5.0 кг на ускорение свободного падения a=9.8 м/с², получим силу F = 49.00 Н.


***2)Бинарная операция %***

In [163]:
m = 5.0
a = 9.8
print('Умножив %.1f кг на ускорение свободного падения %.1f м/с², получим силу F = %.2f Н.' % (m, a, m * a))

Умножив 5.0 кг на ускорение свободного падения 9.8 м/с², получим силу F = 49.00 Н.


***3)Метод .format()***

In [166]:
m = 5.0
a = 9.8
print('Умножив {:.1f} кг на ускорение свободного падения {:.1f} м/с², получим силу F = {:.2f} Н.'.format(m, a, m * a))

Умножив 5.0 кг на ускорение свободного падения 9.8 м/с², получим силу F = 49.00 Н.


- использование синтаксиса f’…{variable=:…}’, где variable – заданная переменная: `{m=:.1f}`, `{a=:.1f}`
- использование синтаксиса f’…{expression=:…}’, где expression – заданное выражение: `{m*a:=.2f}`

## 2.12 Файловый объект

In [265]:
file = open(r'C:\Users\arish\source\repos\Functious\Piligrimi.txt', 'r', encoding='utf-8')
content = file.read()
print(content)
file.close()

Мимо ристалищ, капищ,
мимо храмов и баров,
мимо шикарных кладбищ,
мимо больших базаров,
мира и горя мимо,
мимо Мекки и Рима,
синим солнцем палимы,
идут по земле пилигримы.
Увечны они, горбаты,
голодны, полуодеты,
глаза их полны заката,
сердца их полны рассвета.
За ними поют пустыни,
вспыхивают зарницы,
звезды горят над ними,
и хрипло кричат им птицы:
что мир останется прежним,
да, останется прежним,
ослепительно снежным,
и сомнительно нежным,
мир останется лживым,
мир останется вечным,
может быть, постижимым,
но все-таки бесконечным.
И, значит, не будет толка
от веры в себя да в Бога.
…И, значит, остались только
иллюзия и дорога.
И быть над землей закатам,
и быть над землей рассветам.
Удобрить ее солдатам.
Одобрить ее поэтам.






In [269]:
file = open(r'C:\Users\arish\source\repos\Functious\Piligrimi.txt', 'r', encoding='utf-8')
first_line = file.readline()
print("\nПервая строка (readline):")
print(first_line, end='')
file.close()


Первая строка (readline):
Мимо ристалищ, капищ,


In [271]:
file = open(r'C:\Users\arish\source\repos\Functious\Piligrimi.txt', 'r', encoding='utf-8')
lines = file.readlines()
print("\nВсе строки (readlines):")
for line in lines:
    print(line, end='')
file.close()  


Все строки (readlines):
Мимо ристалищ, капищ,
мимо храмов и баров,
мимо шикарных кладбищ,
мимо больших базаров,
мира и горя мимо,
мимо Мекки и Рима,
синим солнцем палимы,
идут по земле пилигримы.
Увечны они, горбаты,
голодны, полуодеты,
глаза их полны заката,
сердца их полны рассвета.
За ними поют пустыни,
вспыхивают зарницы,
звезды горят над ними,
и хрипло кричат им птицы:
что мир останется прежним,
да, останется прежним,
ослепительно снежным,
и сомнительно нежным,
мир останется лживым,
мир останется вечным,
может быть, постижимым,
но все-таки бесконечным.
И, значит, не будет толка
от веры в себя да в Бога.
…И, значит, остались только
иллюзия и дорога.
И быть над землей закатам,
и быть над землей рассветам.
Удобрить ее солдатам.
Одобрить ее поэтам.





In [273]:
file = open(r'C:\Users\arish\source\repos\Functious\Piligrimi.txt', 'a', encoding='utf-8')
file.write("\nИосиф Бродский1.\n")
print("\nДобавлена строка с помощью write.")
file.close()  


Добавлена строка с помощью write.


In [275]:
file = open(r'C:\Users\arish\source\repos\Functious\Piligrimi.txt', 'a', encoding='utf-8')
new_lines = ["Пилигримы.\n", "1958 г..\n"]
file.writelines(new_lines)
print("Добавлены строки с помощью writelines.")
file.close() 

Добавлены строки с помощью writelines.


In [277]:
file = open(r'C:\Users\arish\source\repos\Functious\Piligrimi.txt', 'r', encoding='utf-8')
updated_content = file.read()
print("\nОбновленное содержимое файла (read):")
print(updated_content)
file.close() 


Обновленное содержимое файла (read):
Мимо ристалищ, капищ,
мимо храмов и баров,
мимо шикарных кладбищ,
мимо больших базаров,
мира и горя мимо,
мимо Мекки и Рима,
синим солнцем палимы,
идут по земле пилигримы.
Увечны они, горбаты,
голодны, полуодеты,
глаза их полны заката,
сердца их полны рассвета.
За ними поют пустыни,
вспыхивают зарницы,
звезды горят над ними,
и хрипло кричат им птицы:
что мир останется прежним,
да, останется прежним,
ослепительно снежным,
и сомнительно нежным,
мир останется лживым,
мир останется вечным,
может быть, постижимым,
но все-таки бесконечным.
И, значит, не будет толка
от веры в себя да в Бога.
…И, значит, остались только
иллюзия и дорога.
И быть над землей закатам,
и быть над землей рассветам.
Удобрить ее солдатам.
Одобрить ее поэтам.




Иосиф Бродский1.
Пилигримы.
1958 г..



## Задание 2.3

*1 ошибка*

In [282]:
print('\c \xc6')

\c Æ


<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\arish\AppData\Local\Temp\ipykernel_6792\1155648579.py:1: SyntaxWarning: invalid escape sequence '\c'
  print('\c \xc6')


Ошибка появляется потому что питон не распознает символ `c` после \ в качестве допустимого управляющего кода.Нужно использовать raw-строку

In [288]:
print(r'\c \xc6')

\c \xc6


*2 ошибка*

In [293]:
str1= 'String'
str1[10]

IndexError: string index out of range

Индекс 10 выходит за пределы строки.Можно заполнить строку до нужной длины, указать существующий индекс или написать вывод об ошибке

In [295]:
str1 = 'String'
index = 10

try:
    print(str1[index])
except IndexError:
    print(f"Индекс {index} выходит за пределы строки")

Индекс 10 выходит за пределы строки


*3 ошибка*

In [301]:
[1] + '1'

TypeError: can only concatenate list (not "str") to list

В выражении с операцией сложения + для последовательностей в качестве операндов могут быть использованы только объекты одного и того же типа. Нельзя
использовать последовательности различных типов в операции сложения + из-за строгой типизации объектов в Python.

In [309]:
[1] + [1] #одного типа

[1, 1]

In [311]:
'1'+'1' #одного типа

'11'

*4 ошибка*

In [314]:
dict1['two']

NameError: name 'dict1' is not defined

Ошибка возникает, потому что  ключ 'two' отсутствует в словаре dict1. Перед обращением к ключу можно проверить, существует ли он в словаре:

In [316]:
dict1 = {'one': 1, 'three': 3}
if 'two' in dict1:
    print(dict1['two'])
else:
    print("Ключа 'two' нет в словаре")

Ключа 'two' нет в словаре


*5 ошибка*

In [319]:
t = [1,2], {1:2}, {1,2}; 
t[0] = 0

TypeError: 'tuple' object does not support item assignment

Кортеж является неизменяемым типом данных, поэтому мы не можем изменить его элементы после создания. Можно использовать список вместо кортежа 

In [327]:
t = [[1, 2], {1: 2}, {1, 2}]  
t[0] = 0 
print(t)  

[0, {1: 2}, {1, 2}]


*6 ошибка*

In [336]:
{1, 'str', (1,)}.add([1])

TypeError: unhashable type: 'list'

Элементами множества могут являться только объекты неизменяемых типов: число, строка, кортеж. 

*7 ошибка*

In [347]:
dict1 = dict(one=1, two=2)
dict1.keys(), dict1.values(), dict1.items()
print(dict1.get('one'), dict1.get('three'))
dict1['three']

TypeError: 'dict' object is not callable

Ключ отсутствует в словаре

*8 ошибка*

In [355]:
s='string'
print(s, s.find('-'))

string -1


In [357]:
s.index('-')

ValueError: substring not found

Результаты выполнения методов find и index отличаются в случае, когда искомая подстрока отсутствует в строке. Метод find возвращает -1, если подстрока не найдена, а метод index вызывает ошибку 

*9 ошибка*

In [368]:
a = 1 
a, z

NameError: name 'z' is not defined

Использование переменной до того, как ей было присвоено значение, всегда приведет к ошибке. Сначала присваеваем переменной хначение , потом используем

In [371]:
z=2
a,z

(1, 2)

*10 ошибка*

In [376]:
print(abs(-1))
abs = 5
print(abs(-1))

1


TypeError: 'int' object is not callable

Зарезервированные имена нельзя использовать в качестве имен переменных.

## Задание 3

***Ответы на контрольные вопросы из книги М. Лутца***

**Глава 4**

*1. Назовите четыре основных типа данных Python.*

В Python существует множество типов данных, но из четырех основных типов можно назвать:

1)Числа

In [ ]:
a = 5          # int
b = 3.14       # float
c = 2 + 4j     # complex

2)Списки

In [388]:
list = [1, 3.14, 'cat']

3)Строки

In [392]:
str = "Neskvik s pivom"

4)Словари

In [395]:
dict = {"name": "Vlad", "age": 25}

*2. Почему они называются “основными” типами данных?*

Эти типы данных используются практически в каждой программе на Python. Они являются фундаментальными для решения большинства задач:Числа используются для математических операций, строки — для работы с текстом, списки и словари — для хранения и обработки коллекций данных. Так же эти типы данных встроены в Python и не требуют дополнительных библиотек или модулей для использования.

*3. Что означает “неизменяемость”, и какие три основных типа Python считаются неизменяемыми?*

Если вы попытаетесь изменить неизменяемый объект, то будет создан новый объект с новым значением, а старый останется неизменным.
Неизменяемыми обьектами являются : `Числа`, `строки`, `кортежи`:

In [405]:
a=1
a=2
print(a)

2


In [427]:
s = "word"
s[0] = 'A' 

TypeError: 'str' object does not support item assignment

In [429]:
s = s + " and loose"
print(s)

word and loose


In [431]:
t = (1, 2, 3)
t[0] = 10  

TypeError: 'tuple' object does not support item assignment

In [433]:
t = t + (4,)
print(t)

(1, 2, 3, 4)


*4. Что означает “последовательность”, и какие три типа входят в эту категорию?*

Последовательность — позиционно упорядоченная коллекциея других объектов. Сюда входят `Списки`, `Строки`, `Кортежи`

*5. Что означает “отображение”, и какой основной тип является отображением?*

Отображения представляют собой коллекции других объектов, но они хранят объекты по ключам, а не по относительным позициям.`Словарь`- основной тип является отображения.

*6. Что такое “полиморфизм” и почему о нем нужно заботиться?*

Полиморфизм — это концепция, которая позволяет использовать один интерфейс для работы с разными типами данных или объектами.Он делает код более гибким и вляется важной частью объектно-ориентированного программирования и помогает создавать более чистый и модульный код.

In [445]:
def add(a, b):
    return a + b

print(add(2, 3))  
print(add("Make, ", "tea")) 

5
Make, tea


**Глава 5**

*1. Каким будет значение выражения 2 * (3 + 4) в Python?
  2. Каким будет значение выражения 2 * 3 + 4 в Python?
  3. Каким будет значение выражения 2 + 3 * 4 в Python?*

In [452]:
print(2 * (3 + 4))
print(2 * 3 + 4)
print(2 + 3 * 4)

14
10
14


*4) Какие инструменты можно использовать для нахождения квадратного корня и квадрата числа?*

Квадрат числа можно найти с помощью `**` или функции `pow()`

In [461]:
a1 = 5 ** 2
print(a1)  

a2 = pow(5, 2)
print(a2)  

25
25


Квадратный корень можно найти с помощью:
Оператора `**` (в степень 0.5) , функции `pow()` (в степень 0.5) , функции `math.sqrt()` из модуля math.


In [464]:
import math

b1 = 25 ** 0.5
print(b1) 

b2 = math.sqrt(25)
print(b2) 

b3 = pow(25, 0.5)
print(b3) 

5.0
5.0
5.0


Для массива чисел можно использовать библиотеку `numpy`

In [471]:
import numpy as np

square_np = np.square(5)
print(square_np)  

sqrt_np = np.sqrt(25)
print(sqrt_np) 

25
5.0


*5. Каким будет тип результата выражения 1 + 2.0 + 3?*

In [481]:
x=1+ 2.0 +3
print(x)
print (type(x))

6.0
<class 'float'>


*6. Как можно усекать и округлять число с плавающей точкой?*

Усечение : функции `int (N)` и `math, trune (N)`, а округление — функция `round (N, digits)`

In [486]:
import math
x = 3.14

r1 = math.trunc(x)
print(r1)  

r2 = int(x)
print(r2)

3
3


In [488]:
print(round(x))

3


*7.Как можно преобразовывать целое число в число с плавающей точкой?*

Функция `float()`

In [496]:
n=5
print(type(n))
n= float(n)
print(type(n))

<class 'int'>
<class 'float'>


*8. Как можно отображать целое число в восьмеричной, шестнадцатеричной или двоичной форме?*

Восьмеричная система: `oct(x)`, шестнадцатеричная система: `hex(x)`, двоичная система: `bin(x)`,форматированиe  строк `%` и строковый метод `format`

In [501]:
h=10
print(oct(h))
print(hex(h))
print(bin(h))

print(f"{h:o}")  
print(f"{h:x}")  
print(f"{h:b}")  


print("{:o}".format(h))  
print("{:x}".format(h))  
print("{:b}".format(h))  


0o12
0xa
0b1010
12
a
1010
12
a
1010


*9. Как можно преобразовывать строку восьмеричных, шестнадцатеричных или двоичных цифр в простое целое число?*

Функция `int (S, base)` , функция `eval (S)`

In [506]:
octal_str = "0o52"
integer1 = int(octal_str, 8)
print(integer1)  

hex_str = "0x2a"
integer2 = int(hex_str, 16)
print(integer2)  

binary_str = "0b101010"
integer3 = int(binary_str, 2)
print(integer3)  

42
42
42


In [508]:
octal_str = "0o52"
integer1 = eval(octal_str)
print(integer1)  

hex_str = "0x2a"
integer2 = eval(hex_str)
print(integer2)  

binary_str = "0b101010"
integer3 = eval(binary_str)
print(integer3) 

42
42
42


**Глава 6**

*1. Взгляните на следующие три оператора. Изменяют ли они значение, выводимое для А?*

In [529]:
A = "spam"
B = A
B = "shrubbery"

print(A)
print(B)

spam
shrubbery


Изначально A и B указывали на один и тот же объект "spam", но в Python имена переменных не связываются друг с другом. Изменение одной переменной не влияет на другую, так как каждая переменная просто ссылается на свой объект. Таким образом, после присваивания B = "shrubbery", A по-прежнему указывает на "spam", а B — на "shrubbery"

*2. Взгляните на приведенные ниже три оператора. Изменяют ли они значение, выводимое для А?*

In [539]:
A = ["spam"]
B = A
B[0] = "shrubbery"

print(A)  
print(B)  

['shrubbery']
['shrubbery']


Поскольку списки в Python являются изменяемыми объектами, изменение списка через одну переменную (B) отражается на другой переменной (A), если они ссылаются на один и тот же объект.

*3. Как насчет показанных далее трех операторов — изменяется ли А теперь?*

In [543]:
A = ["spam"]
B = A[:]
B[0] = "shrubbery"

print( A) 
print( B)  

['spam']
['shrubbery']


Нет, значение переменной A не изменяется, так как B ссылается на новый список, созданный с помощью среза A[:]. Изменения в B не влияют на A

**Глава 7**

*1. Можно ли использовать строковый метод find для поиска в списке?*

Метод `find()` предназначен только для работы со строками и ищет подстроку в строке

In [551]:
list = [1,2,3]
result = list.find(2)

AttributeError: 'list' object has no attribute 'find'

*4. Как бы вы могли изменить строку в Python?*

Cтроки неизменяемы. Можно добиться похожего результата используя конкатенацию, методы строк, срезы, форматирование или преобразование в список

In [554]:
s = "Pupa"
s = s + "lupa"  
print(s) 

Pupalupa


In [556]:
s = "Pupa lupa"
s = s[:5] 
print(s)

Pupa 


*6. Сколько символов имеется в строке "a\nb\xlf\000d"?*

In [559]:
s = "a\nb\x1f\000d"
print(len(s))  # Вывод: 6

6


*7. Почему вы использовали бы модуль string вместо вызова строковых методов?*

Модуль string в Python используют ради констант и функций, которые могут быть полезны в некоторых ситуациях. 

In [566]:
import string

print(string.digits)        
print(string.punctuation)   

0123456789
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


Но для большинства повседневных задач строковые методы (например, str.upper(), str.replace()) используются чаще

In [568]:
s = "hi, YOU"
print(s.upper()) 
print(s.lower())  

HI, YOU
hi, you


**Глава 8**

*1. Назовите два способа построения списка, содержащего пять целочисленных нулей*

Cписковый литерал  и умножение списка:

In [573]:
list1=[0,0,0,0,0]
print(list1)

list2 = [0]*5
print(list2)

[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]


*2. Назовите два способа построения словаря с двумя ключами, ’ а ’ и ’Ь’, с каждым из которых ассоциировано значение 0.*

Использование литерального выражения и серия присваиваний

In [592]:
dict1 = {'a': 0, 'b': 0}
print(dict1) 


{'a': 0, 'b': 0}


In [602]:
dict2 = {}  
dict2['а'] = 0  
dict2['b'] = 0 
print(dict2)  

{'а': 0, 'b': 0}


*3. Назовите четыре операции, которые изменяют списковый объект на месте*

`append` `extend` `sort` `reverse` , еще можно впомнить `insert` `remove` `pop` `del`

In [609]:
my_list = [3, 1, 4, 1, 5, 9]
print("Начальный список:", my_list) 

my_list.append(2)
print("После append(2):", my_list) 

my_list.extend([6, 5])
print("После extend([6, 5]):", my_list) 

my_list.insert(2, 7)
print("После insert(2, 7):", my_list)  

my_list.remove(1)
print("После remove(1):", my_list)  

pop_element = my_list.pop(3)
print("После pop(3):", my_list)  
print("Удаленный элемент:", pop_element)  

del my_list[0]
print("После del my_list[0]:", my_list)

my_list.sort()
print("После sort():", my_list) 

my_list.reverse()
print("После reverse():", my_list) 

Начальный список: [3, 1, 4, 1, 5, 9]
После append(2): [3, 1, 4, 1, 5, 9, 2]
После extend([6, 5]): [3, 1, 4, 1, 5, 9, 2, 6, 5]
После insert(2, 7): [3, 1, 7, 4, 1, 5, 9, 2, 6, 5]
После remove(1): [3, 7, 4, 1, 5, 9, 2, 6, 5]
После pop(3): [3, 7, 4, 5, 9, 2, 6, 5]
Удаленный элемент: 1
После del my_list[0]: [7, 4, 5, 9, 2, 6, 5]
После sort(): [2, 4, 5, 5, 6, 7, 9]
После reverse(): [9, 7, 6, 5, 5, 4, 2]


*4. Назовите четыре операции, которые изменяют словарный объект на месте*

Добавление или обновление элементов: Присваивание по ключу, `update()`; удаление элементов: `del`, `pop()`

In [623]:
dict1 = {'a': 1, 'b': 2}

dict1['c'] = 3 
dict1['a'] = 10 
print(dict1)


{'a': 10, 'b': 2, 'c': 3}


In [625]:
dict2 = {'a': 7, 'b': 6}
dict2.update({'d': 4, 'e': 5})
print(dict2)

{'a': 7, 'b': 6, 'd': 4, 'e': 5}


In [627]:
dict3 = {'a': 1, 'b': 2, 'c': 3}

del dict3['a']
dict3.pop('b')
print(dict3)

{'c': 3}


*5. Почему вы можете использовать словарь вместо списка?*

Словари обычно лучше подходят для работы с данными, которые имеют метки (например, записи с именованными полями), тогда как списки больше подходят для коллекций данных без меток (например, список всех файлов в каталоге). Поиск в словаре, как правило, выполняется быстрее, чем в списке, хотя это может зависеть от конкретной программы

**Глава 9**

*1. Как определить размер кортежа? Почему этот инструмент находится там, где он есть?*

С помощью функции `len` можно узнать длину кортежа. `len` является встроенной функцией, а не методом типа, потому что она применяется к
множеству разных типов объектов

In [634]:
tuple = (1, 2, 3, 4, 5)
print(len(tuple))

5


*2. Напишите выражение, которое изменяет первый элемент в кортеже. В процессе кортеж (4,5,6) должен стать (1,5,6).*

Кортежи являются неизменяемыми объектами, поэтому можно создать новый кортеж на основе существующего, заменив нужные элементы

In [638]:
tuple1 = (4, 5, 6)
tuple2 = (1, *tuple1[1:])  
print(tuple2) 

(1, 5, 6)


*6. Когда Python считает объект истинным?*

Объект считается истинным, если он представляет собой либо ненулевое число, либо непустую коллекцию

In [641]:
if not 0:
    print("0 is falsy") 
if [1, 2, 3]:
    print("Non-empty list is truthy")

0 is falsy
Non-empty list is truthy
